// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the native boundary for settings and journal-file access.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChooseStorageDirectory opens the native folder picker.
 */
export function ChooseStorageDirectory(): $CancellablePromise<string> {
    return $Call.ByID(4241878388);
}

/**
 * ConfirmWindowClose closes the calling window after the frontend has either
 * saved or explicitly discarded its edits.
 */
export function ConfirmWindowClose(): $CancellablePromise<void> {
    return $Call.ByID(2428711757);
}

/**
 * CreateDay creates the base file set for a validated date.
 */
export function CreateDay(date: string): $CancellablePromise<$models.DayData> {
    return $Call.ByID(546867421, date).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateDoingStream adds the next numbered Doing file for an open day. The
 * exclusive create keeps simultaneous shortcuts or app instances from choosing
 * the same filename.
 */
export function CreateDoingStream(date: string): $CancellablePromise<$models.JournalFile> {
    return $Call.ByID(4138783196, date).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateToday creates today's base Doing and Todo files without truncating
 * anything that already exists.
 */
export function CreateToday(): $CancellablePromise<$models.DayData> {
    return $Call.ByID(3313787806).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetDebugLogDirectory returns the private application-support folder used by
 * the flight recorder. It does not create the folder until logging is enabled
 * or the user explicitly asks to reveal it.
 */
export function GetDebugLogDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2452506095);
}

/**
 * GetSettings returns persisted settings or the default ~/Documents/JM root.
 */
export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(2554697378).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListDays discovers dates represented by either Doing or Todo files.
 */
export function ListDays(): $CancellablePromise<$models.DaySummary[]> {
    return $Call.ByID(2876593206).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * OpenDay reads an existing day's plain-text files without changing them.
 */
export function OpenDay(date: string): $CancellablePromise<$models.DayData> {
    return $Call.ByID(474293513, date).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * OpenDayWindow focuses an existing window for the date or opens a new one.
 */
export function OpenDayWindow(date: string): $CancellablePromise<string> {
    return $Call.ByID(2291450649, date);
}

/**
 * OpenDebugLogFolder reveals the recorder folder in Finder or the platform's
 * equivalent file manager.
 */
export function OpenDebugLogFolder(): $CancellablePromise<void> {
    return $Call.ByID(132951502);
}

/**
 * OpenSettingsWindow focuses the application-wide settings window or opens it.
 */
export function OpenSettingsWindow(): $CancellablePromise<string> {
    return $Call.ByID(3185921024);
}

/**
 * ReadJournalFiles returns fresh snapshots for open panes. The frontend polls
 * this in one batch so changes made by editors, scripts, or coding agents are
 * noticed without installing a long-lived filesystem watcher.
 */
export function ReadJournalFiles(paths: string[]): $CancellablePromise<$models.JournalFile[]> {
    return $Call.ByID(2433091695, paths).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * RecordDebugEvents appends a short frontend batch to the active JSONL log.
 * Calls are ignored when debug mode is disabled so a stale window cannot keep
 * collecting journal content after the setting has been turned off.
 */
export function RecordDebugEvents(events: $models.DebugEvent[]): $CancellablePromise<void> {
    return $Call.ByID(2072820646, events);
}

/**
 * SaveFile atomically saves a journal file inside the configured Doing/Todo
 * folders. Unless force is explicit, the save only proceeds when disk still
 * matches the version the editor started from.
 */
export function SaveFile(path: string, content: string, expectedContent: string, force: boolean): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(1396636678, path, content, expectedContent, force).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * SaveSettings persists a journal root and creates its Doing/Todo folders.
 */
export function SaveSettings(settings: $models.Settings): $CancellablePromise<$models.Settings> {
    return $Call.ByID(1949631069, settings).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SetEditorFont persists an editor font selected from the native View menu.
 */
export function SetEditorFont(font: string): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3401608479, font).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DayData.createFrom;
const $$createType1 = $models.JournalFile.createFrom;
const $$createType2 = $models.Settings.createFrom;
const $$createType3 = $models.DaySummary.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($$createType1);
const $$createType6 = $models.SaveResult.createFrom;
