// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DayData contains the todo and all Doing streams discovered for one date.
 */
export class DayData {
    "date": string;
    "todo": JournalFile;
    "doing": JournalFile[];

    /** Creates a new DayData instance. */
    constructor($$source: Partial<DayData> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("todo" in $$source)) {
            this["todo"] = (new JournalFile());
        }
        if (!("doing" in $$source)) {
            this["doing"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DayData instance from a string or object.
     */
    static createFrom($$source: any = {}): DayData {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("todo" in $$parsedSource) {
            $$parsedSource["todo"] = $$createField1_0($$parsedSource["todo"]);
        }
        if ("doing" in $$parsedSource) {
            $$parsedSource["doing"] = $$createField2_0($$parsedSource["doing"]);
        }
        return new DayData($$parsedSource as Partial<DayData>);
    }
}

/**
 * DaySummary is the information needed by the welcome screen.
 */
export class DaySummary {
    "date": string;
    "doingCount": number;
    "hasTodo": boolean;

    /** Creates a new DaySummary instance. */
    constructor($$source: Partial<DaySummary> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("doingCount" in $$source)) {
            this["doingCount"] = 0;
        }
        if (!("hasTodo" in $$source)) {
            this["hasTodo"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DaySummary instance from a string or object.
     */
    static createFrom($$source: any = {}): DaySummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DaySummary($$parsedSource as Partial<DaySummary>);
    }
}

/**
 * JournalFile is one plain-text file displayed by the day workspace.
 */
export class JournalFile {
    "path": string;
    "name": string;
    "content": string;
    "exists": boolean;
    "streamIndex": number;

    /** Creates a new JournalFile instance. */
    constructor($$source: Partial<JournalFile> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("streamIndex" in $$source)) {
            this["streamIndex"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JournalFile instance from a string or object.
     */
    static createFrom($$source: any = {}): JournalFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JournalFile($$parsedSource as Partial<JournalFile>);
    }
}

/**
 * SaveResult reports whether an optimistic journal save reached disk. When
 * Conflict is true, Content is the newer disk version that was preserved.
 */
export class SaveResult {
    "saved": boolean;
    "conflict": boolean;
    "content": string;
    "exists": boolean;

    /** Creates a new SaveResult instance. */
    constructor($$source: Partial<SaveResult> = {}) {
        if (!("saved" in $$source)) {
            this["saved"] = false;
        }
        if (!("conflict" in $$source)) {
            this["conflict"] = false;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveResult($$parsedSource as Partial<SaveResult>);
    }
}

/**
 * Settings contains the small amount of application state that is not stored
 * in the journal files themselves.
 */
export class Settings {
    "storageRoot": string;
    "editorFont": string;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("storageRoot" in $$source)) {
            this["storageRoot"] = "";
        }
        if (!("editorFont" in $$source)) {
            this["editorFont"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

// Private type creation functions
const $$createType0 = JournalFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
