// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseStorageDirectory() {
  return window['go']['main']['App']['ChooseStorageDirectory']();
}

export function CreateDay(arg1) {
  return window['go']['main']['App']['CreateDay'](arg1);
}

export function CreateDoingStream(arg1) {
  return window['go']['main']['App']['CreateDoingStream'](arg1);
}

export function CreateToday() {
  return window['go']['main']['App']['CreateToday']();
}

export function GetLaunchDate() {
  return window['go']['main']['App']['GetLaunchDate']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListDays() {
  return window['go']['main']['App']['ListDays']();
}

export function OpenDay(arg1) {
  return window['go']['main']['App']['OpenDay'](arg1);
}

export function OpenDayWindow(arg1) {
  return window['go']['main']['App']['OpenDayWindow'](arg1);
}

export function ReadJournalFiles(arg1) {
  return window['go']['main']['App']['ReadJournalFiles'](arg1);
}

export function SaveFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3, arg4);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetEditorFont(arg1) {
  return window['go']['main']['App']['SetEditorFont'](arg1);
}
