// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseStorageDirectory():Promise<string>;

export function CreateDay(arg1:string):Promise<main.DayData>;

export function CreateDoingStream(arg1:string):Promise<main.JournalFile>;

export function CreateToday():Promise<main.DayData>;

export function GetLaunchDate():Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function ListDays():Promise<Array<main.DaySummary>>;

export function OpenDay(arg1:string):Promise<main.DayData>;

export function OpenDayWindow(arg1:string):Promise<string>;

export function ReadJournalFiles(arg1:Array<string>):Promise<Array<main.JournalFile>>;

export function SaveFile(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<main.SaveResult>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;

export function SetEditorFont(arg1:string):Promise<main.Settings>;
